"""Phase 6: host-side PR export (project brief, section 7).

Commits the agent's work from the ephemeral scratch directory and opens a
pull request using the macOS user's own Git/gh credentials.

### Why this runs on the HOST, never in the sandbox

This deliberately bypasses the container. The sandbox is blind to host
credentials precisely so that agent-authored code cannot exfiltrate them
(brief section 2.2). Pushing requires a GitHub token, so the push must
happen outside the sandbox -- otherwise an Indirect Prompt Injection trap
could reach a real PAT.

The agent never sees, and never influences, anything in this module.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path


class ExportError(RuntimeError):
    """Raised when a PR cannot be created."""


@dataclass
class ExportResult:
    """Outcome of a PR export."""

    branch: str
    commit_sha: str
    pr_url: str | None
    files_changed: list[str]
    pushed: bool


def _git(args: list[str], cwd: Path, *, check: bool = True) -> str:
    proc = subprocess.run(
        ["git"] + args, cwd=cwd, capture_output=True, text=True, timeout=300
    )
    if check and proc.returncode != 0:
        raise ExportError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def changed_files(workspace: Path, *, baseline_commit: str) -> list[str]:
    """Files the agent added, modified, or deleted since the baseline."""
    _git(["add", "-A"], cwd=workspace)
    diff = _git(
        ["diff", "--name-only", baseline_commit, "--cached"], cwd=workspace
    )
    return [line for line in diff.splitlines() if line.strip()]


def commit_agent_work(
    workspace: Path,
    *,
    baseline_commit: str,
    task_id: str,
    run_id: str,
    model_label: str,
) -> tuple[str, list[str]]:
    """Stage and commit whatever the agent changed.

    Returns (commit_sha, changed_files). Raises if nothing changed, since an
    empty PR is not worth opening.
    """
    files = changed_files(workspace, baseline_commit=baseline_commit)
    if not files:
        raise ExportError(
            f"Agent made no changes for task '{task_id}'; nothing to export."
        )

    message = (
        f"agent({task_id}): automated changes from run {run_id}\n\n"
        f"Model: {model_label}\n"
        f"Task: {task_id}\n"
        f"Run: {run_id}\n"
        f"Files changed: {len(files)}\n\n"
        f"Generated by the Agentic IDE Evaluation Suite. Not human-reviewed."
    )
    _git(["commit", "-q", "-m", message], cwd=workspace)
    return _git(["rev-parse", "HEAD"], cwd=workspace), files


def build_pr_body(
    *,
    task_id: str,
    run_id: str,
    model_label: str,
    benchmark_valid: bool,
    scorecard: dict | None,
    files: list[str],
) -> str:
    """Compose the PR description, including the local scorecard."""
    lines = [
        "## Automated agent run",
        "",
        "> **This PR was generated by an autonomous agent and has not been "
        "human-reviewed.** CI re-runs the graders independently to verify "
        "the scores below.",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Task | `{task_id}` |",
        f"| Run ID | `{run_id}` |",
        f"| Model | `{model_label}` |",
        f"| Benchmark-valid | {'yes' if benchmark_valid else '**no (dev model)**'} |",
        f"| Files changed | {len(files)} |",
    ]

    if not benchmark_valid:
        lines += [
            "",
            "⚠️ This run used a **non-benchmark-valid** model profile "
            "(a cheap plumbing-validation model). Its scores must not be "
            "used for framework comparison.",
        ]

    if scorecard:
        lines += ["", "### Local scores (host-computed)", ""]
        lines += ["| Dimension | Score | Weight | Contribution |", "|---|---|---|---|"]
        weights = scorecard.get("weights", {})
        contributions = scorecard.get("weighted_contributions", {})
        for name, value in scorecard.get("dimensions", {}).items():
            lines.append(
                f"| {name} | {value} | {weights.get(name, '')} | "
                f"{contributions.get(name, '')} |"
            )
        lines += ["", f"**Final score: {scorecard.get('final_score')}**"]
        if not scorecard.get("reliable", True):
            lines += [
                "",
                "⚠️ **Provisional:** at least one grader failed to run, so a "
                "dimension may read 0 without the agent actually scoring 0.",
            ]
            for error in scorecard.get("grader_errors", []):
                lines.append(f"- `{error}`")

    lines += ["", "### Files changed", ""]
    lines += [f"- `{path}`" for path in files[:40]]
    if len(files) > 40:
        lines.append(f"- ... and {len(files) - 40} more")

    return "\n".join(lines)


def export_pr(
    workspace: Path,
    *,
    baseline_commit: str,
    task_id: str,
    run_id: str,
    model_label: str,
    benchmark_valid: bool,
    remote_url: str,
    base_branch: str = "main",
    scorecard: dict | None = None,
    dry_run: bool = True,
) -> ExportResult:
    """Commit, push, and open a PR from the scratch workspace.

    `dry_run` defaults to True: opening real pull requests is a
    side-effecting operation on a shared repository, so it must be opted
    into explicitly rather than triggered by an accidental invocation.
    """
    branch = f"agent/{task_id}/{run_id}"
    _git(["checkout", "-q", "-b", branch], cwd=workspace)

    commit_sha, files = commit_agent_work(
        workspace,
        baseline_commit=baseline_commit,
        task_id=task_id,
        run_id=run_id,
        model_label=model_label,
    )

    body = build_pr_body(
        task_id=task_id,
        run_id=run_id,
        model_label=model_label,
        benchmark_valid=benchmark_valid,
        scorecard=scorecard,
        files=files,
    )

    if dry_run:
        print("[pr_export] DRY RUN -- nothing pushed.")
        print(f"[pr_export]   branch : {branch}")
        print(f"[pr_export]   commit : {commit_sha[:12]}")
        print(f"[pr_export]   files  : {len(files)}")
        print(f"[pr_export]   remote : {remote_url}")
        return ExportResult(
            branch=branch,
            commit_sha=commit_sha,
            pr_url=None,
            files_changed=files,
            pushed=False,
        )

    # The scratch dir has no remote: it was created by copying a directory
    # or by cloning and then discarding history.
    _git(["remote", "remove", "origin"], cwd=workspace, check=False)
    _git(["remote", "add", "origin", remote_url], cwd=workspace)
    _git(["push", "-q", "--set-upstream", "origin", branch], cwd=workspace)

    proc = subprocess.run(
        [
            "gh", "pr", "create",
            "--repo", _repo_slug(remote_url),
            "--base", base_branch,
            "--head", branch,
            "--title", f"agent({task_id}): automated run {run_id}",
            "--body", body,
        ],
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if proc.returncode != 0:
        raise ExportError(f"gh pr create failed: {proc.stderr.strip()}")

    pr_url = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else None

    return ExportResult(
        branch=branch,
        commit_sha=commit_sha,
        pr_url=pr_url,
        files_changed=files,
        pushed=True,
    )


def _repo_slug(remote_url: str) -> str:
    """Extract `owner/name` from an HTTPS or SSH remote URL."""
    cleaned = remote_url.removesuffix(".git")
    if cleaned.startswith("git@"):
        return cleaned.split(":", 1)[-1]
    parts = cleaned.rstrip("/").split("/")
    if len(parts) < 2:
        raise ExportError(f"Cannot parse repo slug from '{remote_url}'")
    return f"{parts[-2]}/{parts[-1]}"
